# fly.toml app configuration file generated for domain-monitor on 2025-07-24T20:23:20+06:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'domain-monitor'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = "30s"
    method = 'GET'
    path = '/api/health'
    protocol = 'http'
    tls_skip_verify = false
    

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
